# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "http://blog.findemor.es"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://findemor.github.io/findemor.blog"
#baseurl: "/findemor.blog"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: blog.findemor

# Short description of your site
#description: Por tanto quiso que los corazones de los Hombres buscaran siempre más allá y no encontraran reposo en el mundo.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  #Acerca de...: "aboutme"
  #Resources:
  #  - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
  #  - Learn markdown: "http://www.markdowntutorial.com/"
  #  - GitHub Pages: "https://pages.github.com/"
  Blog: "https://blog.findemor.es"
  Sobre mi: "https://www.findemor.es"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/findemor-logo.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: "/img/front-big.jpg"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#3d387d"
navbar-text-col: "#ffffff"
navbar-children-col: "#3d387d"
navbar-hover-col: "#ffb83a"
page-col: "#FFFFFF"
link-col: "#3d387d" 
hover-col: "#f14640"
post-hover-col: "#e4723e" 
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#3d387d" 
#azul oscuro 18122a
#gris oscuro 404040
#amarillo ffb83a
# naranja e4723e
# titulos naranjas f14640
# titulos azules y barra superior 3d387d

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/front-big.jpg"
# footer-img: "/img/bgimage.png"
# page-img: "/img/front-big.jpg"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: findemor

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
# email: "contacto@findemor.es"
#  facebook: daattali
  github: findemor
  twitter: findemor
#  reddit: yourname
#  google-plus: +DeanAttali
  linkedin: manueljgs
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
  instagram: findemor.nomedhel
  youtube: user/findemor
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
  twitch: findemor
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "findemor.es"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-9584202-6"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: "UA-9584202-6"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "blog-findemor"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
